# Generated by Django 3.2.17 on 2023-02-10 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['c_time'], 'verbose_name': '用户', 'verbose_name_plural': '用户yy'},
        ),
    ]
